export const PLANT_ITEMS = [
  "Panel",
  "Inverter",
  "Rafter",
  "Perlin",
  "Leg 6ft",
  "Leg 8ft",
  "Base Plate",
  "Fastener",
  "Nut Bolts",
  "Spring Bolt",
  "Spring",
  "ACDB",
  "DCDB",
  "DC Wire 4 mm",
  "AC Wire 4 mm",
  "LA Wire 16 mm",
  "Armoured Wire 12 mm",
  "L Clamp",
  "U Clamp",
  "MC4 Connector",
  "PVC Pipe 25 mm",
  "L Bend",
  "U Bend",
  "T Bend",
  "Catchup 25 mm",
  "Catchup 12 mm",
  "Earthing Kit",
  "Transportation",
  "Civil Material",
  "Installation Charges",
  "Vendor Charges",
  "Load Extension",
  "Net Metering",
  "JE"
];